/**
 * Wagti platform business model — single source of truth.
 *
 * This must never be duplicated/hardcoded elsewhere (finance pages, admin
 * dashboard, marketing pricing, etc). Everything that needs to compute a
 * platform fee, a threshold, or a currency label imports from here.
 *
 * NOTE: values below are the prototype's best-known figures per the product
 * brief. They are trivially editable in one place and are NOT wired to any
 * real payment processor — see AUDIT.md for what a production implementation
 * requires (metering, invoicing, reconciliation).
 */

export const platformConfig = {
  currency: "MAD" as const,

  /** Flat platform fee charged per customer booking/service (MAD). */
  customerFeePerBooking: 2,

  /** Flat platform fee charged per completed/managed service on the salon side (MAD). */
  salonFeePerService: 2,

  /**
   * High-volume relief: once a salon crosses `volumeThreshold` completed
   * services within a rolling `thresholdPeriodDays` window, the salon-side
   * fee (salonFeePerService) stops applying for the remainder of the
   * current calendar month.
   */
  volumeThreshold: 300,
  thresholdPeriodDays: 14,

  /**
   * Legacy/placeholder monthly SaaS plans. These are NOT part of the active
   * per-transaction business model above and must stay clearly labelled as
   * optional/future in any UI that surfaces them (see pricing-section.tsx).
   */
  legacySaasPlansActive: false,
} as const;

export type PlatformConfig = typeof platformConfig;

/**
 * Computes the platform-side fee owed for a single completed service,
 * given how many services that salon has already completed in the current
 * rolling volume window.
 */
export function salonFeeForService(servicesInWindow: number): number {
  if (servicesInWindow >= platformConfig.volumeThreshold) return 0;
  return platformConfig.salonFeePerService;
}

/** Platform fee collected from the customer side for one booking. */
export function customerFeeForBooking(): number {
  return platformConfig.customerFeePerBooking;
}

/**
 * Estimates total platform revenue generated by a salon over a set of
 * completed bookings, applying the volume-threshold relief in booking
 * order (deterministic, order-of-array).
 */
export function estimatePlatformRevenue(completedBookingsCount: number): {
  customerFees: number;
  salonFees: number;
  total: number;
} {
  const customerFees = completedBookingsCount * platformConfig.customerFeePerBooking;
  const billableServices = Math.min(completedBookingsCount, platformConfig.volumeThreshold);
  const salonFees = billableServices * platformConfig.salonFeePerService;
  return { customerFees, salonFees, total: customerFees + salonFees };
}
